version: '3'
services:
  math-service1:
    build: ./math_py
    ports:
      - 5001:5000
  
  math-service2:
    build: ./math_py
    ports:
      - 5002:5000

  string-service:
    build: ./string_py
    ports:
      - 5003:5000

  db:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning